### ISSUE TITLE
PySide 6.8 fails with undefined symbol

### ISSUE THREAD

**Issue by junalmeida** [flathub/io.qt.PySide.BaseApp#11] opened 2024-12-14 23:21 UTC
Trying to use latest PySide 6.8 as a flatpak base, but getting the following import error: 

```
ImportError: /app/lib/python3.12/site-packages/PySide6/QtGui.abi3.so: undefined symbol: _ZN10QRhiBuffer38fullDynamicBufferUpdateForCurrentFrameEPKv, version Qt_6_PRIVATE_API
```

The flatpak json looks like this: 
```
    "runtime": "org.kde.Platform",
    "runtime-version": "6.8",
    "sdk": "org.kde.Sdk",
    "base": "io.qt.PySide.BaseApp",
    "base-version": "6.8",
```

Could you please help on giving directions as to why this is happening? 

If I change the versions to 6.7, I don´t get any import errors of PySide6, but it also fails to run with a different error: 

```
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

**Comment by cmaureir** [comment] 2024-12-15 12:08
Hello @junalmeida :wave:
The first missing symbol is a virtual internal function introduced in 6.6, so it should be fine, but it was with your second error message that I believe I know what is happening. You have Qt 6.5.0 in your configuration:
> qt.qpa.plugin: From 6.5.0, xcb-cursor0 ...

That's why both PySide 6.8 and 6.7 fail.

The flatpak package is intended to be used for KDE applications https://develop.kde.org/docs/getting-started/python/python-app/ and it might be that in your configuration you have other settings that are setting the Qt version to 6.5.0 ?

**Comment by junalmeida** [comment] 2024-12-15 15:20
So the `6.5.0` error happens when I set the version to `6.7`. However, I found out why, it was a missing variable from `flatpak-builder --run`. So when I set `6.7`, it is working as expected. 

Only `6.8` fails with the undefined symbol error.

**Comment by cmaureir** [comment] 2024-12-15 20:36
The symbol was added in 6.6, so that means that there are Qt binaries in your build that correspond to 6.5.
Can you share more information?

**Comment by shyamnathp** [comment] 2024-12-16 09:25
The missing symbol indicates that your QtGui.abi3.so is trying to link to a libQt6Gui.so that is not 6.8 at runtime. As i check the symbols list for org.kde.Platform//6.8, the missing symbol is indeed present 

```
shyamnath@ShyamPC:/var/lib/flatpak/runtime/org.kde.Platform/x86_64/6.8/2eb22f8098c7a2df3b26b58d2d83715965cc2b2e735ad7e781d5f173ecf24d8d/files/lib/x86_64-linux-gnu$ nm -D ./libQt6Gui.so | grep QRhiBuffer
000000000047e210 T _ZN10QRhiBuffer12nativeBufferEv@@Qt_6_PRIVATE_API
000000000047e3b0 T _ZN10QRhiBuffer38fullDynamicBufferUpdateForCurrentFrameEPKvj@@Qt_6_PRIVATE_API
000000000047e240 T _ZN10QRhiBuffer41endFullDynamicBufferUpdateForCurrentFrameEv@@Qt_6_PRIVATE_API
000000000047e230 T _ZN10QRhiBuffer43beginFullDynamicBufferUpdateForCurrentFrameEv@@Qt_6_PRIVATE_API
000000000047fa60 T _ZN10QRhiBufferC1EP18QRhiImplementationNS_4TypeE6QFlagsINS_9UsageFlagEEj@@Qt_6_PRIVATE_API
000000000047fa60 T _ZN10QRhiBufferC2EP18QRhiImplementationNS_4TypeE6QFlagsINS_9UsageFlagEEj@@Qt_6_PRIVATE_API
0000000000483700 T 
.....
```


and, for the second error which you solved already, instead of passing via flatpak-builder, you can add     "--env=QT_QPA_PLATFORM=xcb" to the "finish-args" key in your flatpak manifest.

**Comment by junalmeida** [comment] 2024-12-16 09:44
So when I set everything to `6.8` I still get the missing symbol error. I'm not adding any Qt dependency manually, it is just the BaseApp along with the sdk as described in the docs. 

When I set everything to `6.7`, `flatpak-builder --run` miss the variable `XDG_SESSION_TYPE` (which in my system is `wayland`). When I manually pass this variable I see no errors on `6.7` 

The source code is available in https://github.com/junalmeida/webapps_manager

**Comment by shyamnathp** [comment] 2024-12-20 11:16
@junalmeida i was able to reproduce the error. Thanks. 

Fix: https://github.com/flathub/io.qt.PySide.BaseApp/pull/12

Expect delays until the pull request is merged though because the other reviewer is on vacation :). That said, I wish you happy holidays.

**Comment by junalmeida** [comment] 2024-12-20 12:47
Oh that's nice , thanks for looking into it. Happy holidays

**Closed as completed** 2024-12-23 16:08 UTC
Labels: bug
